# Generated by Django 5.0.4 on 2024-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
