# Generated by Django 5.0.4 on 2024-04-13 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_flat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100, unique=True)),
                ('number_plate', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
